apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummy-kyma-module-manager-role
rules:
- apiGroups:
  - operator.acme.io
  resources:
  - dummies
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - operator.acme.io
  resources:
  - dummies/finalizers
  verbs:
  - update
- apiGroups:
  - operator.acme.io
  resources:
  - dummies/status
  verbs:
  - get
  - patch
  - update
